{% set name = "tvb-framework" %}
{% set version = "2.2" %}
{% set sha256 = "dfcdecee7325dd9b75eb63ddca56d046a4a6f3a20a9bc71a609315b6f151d68b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - alembic
    - beautifulsoup4
    - cherrypy
    - cryptography
    - flask
    - flask-restplus
    - formencode
    - h5py
    - Jinja2
    - nibabel
    - numpy
    - pandas
    - pillow
    - psutil
    - pyAesCrypt
    - python-keycloak
    - pytest
    - pytest-benchmark
    - pytest-mock
    - requests
    - scikit-learn
    - scipy
    - simplejson
    - six
    - sqlalchemy
    - tvb-library 2.2
    - tvb-gdist
    - werkzeug 0.16.1
    - psycopg2

test:
  requires:
    - pip
    - pytest
    - pytest-benchmark
    - pytest-mock
    - beautifulsoup4
    - mock 3.0.5

  commands:
    - pip install requests-toolbelt pynrrd simpleitk wget
    - pip install allensdk --no-deps
    - python -m wget -o tvb_data.zip https://zenodo.org/record/4263723/files/tvb_data.zip?download=1
    - python -m zipfile -e tvb_data.zip tvb_data
    - cd tvb_data
    - python setup.py develop
    - pytest -o mock_use_standalone_module=true --pyargs tvb.tests.framework

about:
  home: http://www.thevirtualbrain.com/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A package for performing whole brain simulations
  description: |
    The Virtual Brain Project (TVB Project) has the purpose of offering some |
    modern tools to the Neurosciences community, for computing, simulating |
    and analyzing functional and structural data of human brains. |
    The Virtual Brain framework is a complete framework including: |
    -  a plugable workflow manager; |
    -  a data persistence layer (with a relational DB and File Storage HDF5); |
    -  an HTML5 based user interface; |
    -  visualizers for neuro-science related entities.
    -  REST server and client SDK
  doc_url: http://docs.thevirtualbrain.org/
  dev_url: https://github.com/the-virtual-brain/tvb-root

extra:
  recipe-maintainers:
    - liadomide
    - popaula937
