{% set name = "tvb-framework" %}
{% set version = "2.0.8" %}
{% set sha256 = "95a8585b3095eecbdc8ca389269471a350b6876e732f62c260d75b615d10a237" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - setuptools

  run:
    - python
    - beautifulsoup4
    - cherrypy
    - flask
    - flask-restplus
    - formencode
    - getevent
    - h5py
    - Jinja2
    - Networkx
    - nibabel
    - pillow
    - psutil
    - pyAesCrypt
    - python-keycloak
    - pyunicore
    - pytest
    - pytest-benchmark
    - pytest-mock
    - scikit-learn
    - scipy
    - simplejson
    - sqlalchemy-migrate
    - sqlalchemy
    - tvb-library
    - tvb-data
    - tvb-gdist
    - psycopg2

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs tvb.tests.framework.interfaces.web.controllers.burst_controller_test

about:
  home: http://www.thevirtualbrain.com/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: A package for performing whole brain simulations
  description: |
    The Virtual Brain Project (TVB Project) has the purpose of offering some |
    modern tools to the Neurosciences community, for computing, simulating |
    and analyzing functional and structural data of human brains. |
    The Virtual Brain framework is a complete framework including: |
    -  a plugable workflow manager; |
    -  a data persistence layer (with a relational DB and File Storage); |
    -  an HTML5 based user interface; |
    -  visualizers for neuro-science related entities.
  doc_url: http://docs.thevirtualbrain.org/
  dev_url: https://github.com/the-virtual-brain/tvb-framework

extra:
  recipe-maintainers:
    - liadomide
    - popaula937
