{% set name = "tvb-framework" %}
{% set version = "2.0.9" %}
{% set sha256 = "8a3af6d52e057db901d38c524d4bf1c7f78e793b990b27950d0765b8edf03c61" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - setuptools

  run:
    - python
    - beautifulsoup4
    - cherrypy
    - cryptography
    - flask
    - flask-restplus
    - formencode
    - h5py
    - Jinja2
    - nibabel
    - numpy
    - pandas
    - pillow
    - psutil
    - pyAesCrypt
    - python-keycloak
    - pytest
    - pytest-benchmark
    - pytest-mock
    - requests
    - scikit-learn
    - scipy
    - simplejson
    - six
    - sqlalchemy-migrate
    - sqlalchemy
    - tvb-library
    - tvb-data
    - tvb-gdist
    - werkzeug
    - psycopg2

test:
  requires:
    - pytest 
    - pytest-benchmark
    - pytest-mock
    - beautifulsoup4
  commands:
    - pytest --pyargs tvb.tests.framework.interfaces.web.controllers.burst_controller_test

about:
  home: http://www.thevirtualbrain.com/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A package for performing whole brain simulations
  description: |
    The Virtual Brain Project (TVB Project) has the purpose of offering some |
    modern tools to the Neurosciences community, for computing, simulating |
    and analyzing functional and structural data of human brains. |
    The Virtual Brain framework is a complete framework including: |
    -  a plugable workflow manager; |
    -  a data persistence layer (with a relational DB and File Storage HDF5); |
    -  an HTML5 based user interface; |
    -  visualizers for neuro-science related entities.
    - REST server and client SDK
  doc_url: http://docs.thevirtualbrain.org/
  dev_url: https://github.com/the-virtual-brain/tvb-root

extra:
  recipe-maintainers:
    - liadomide
    - popaula937
